#!/usr/bin/env rdmd
// This file is an rdmd script which generates
// the iana.d file for the human_datetime.d library.
import std.format;

struct IANAZone {
    string name;
    string tz;
    string summer;
}

int main() {
    string[] _out = new string[0];
    IANAZone[] zones = new IANAZone[0];
    string[] uniq = new string[0];

    string top = q{
        // This file is part of the human_datetime.d library.
        // It is generated by `make zones` and tz.csv.

        module iana;

        struct IANAZone {
            string name;
            string tz;
            string summer;
        }

        IANAZone[string] zones = [
    };

    foreach (z; zones) {
       _out ~= format("%s: IANAZone(\"%s\", \"%s\", \"%s\"),", z.name, z.name, z.tz, z.summer);
    }

    return 0;
}
