#!/usr/bin/env rdmd
// This file is an rdmd script which generates
// the iana.d file for the human_datetime.d library.
import std.file;
import std.path;
import std.array;
import std.stdio;
import std.format;
import std.algorithm;
import std.conv : to;

struct IANAZone {
    string name;
    string tz;
    string summer;
}

int main() {
    string[] _out = new string[0];
    IANAZone[] zones = new IANAZone[0];
    string[] uniq = new string[0];

    string top = q{// This file is part of the human_datetime.d library.
// It is generated by `make zones` and tz.csv.

module iana;

struct IANAZone {
    string name;
    string tz;
    string summer;
}

IANAZone[string] zones = [};
    _out ~= top;
    auto f = File("tz.csv");
    foreach (line; f.byLine()) {
        string l = to!string(line);
        string[] row = l.split(",");
        zones ~= IANAZone(row[0], row[3], row[4]);
        uniq ~= row[3];
        uniq ~= row[4];
    }

    foreach (z; zones) {
       _out ~= format("\"%s\": IANAZone(\"%s\", \"%s\", \"%s\"),", z.name, z.name, z.tz, z.summer);
    }
    _out ~= "];\n";
    std.file.write(buildPath("source", "iana.d"), _out.join("\n"));

    //auto unique = uniq.sort().uniq.array;
    //std.file.write("tz.txt", unique.join("\n"));

    return 0;
}
