import os
import csv
from dataclasses import dataclass

@dataclass
class IANAZone:
    name: str
    tz: str
    summer: str

if __name__ == "__main__":
    out: list[str] = []
    zones: list[IANAZone] = []
    uniq: list[str] = []
    with open('tz.csv') as csvfile:
        reader = csv.reader(csvfile)
        for row in reader:
            zones.append(IANAZone(row[0], row[3], row[4]))
            uniq.append(row[3])
            uniq.append(row[4])

    top: str = r"""// This file is part of the human_datetime.d library.
// It is generated by `make zones` and tz.csv.

module timezones;

struct IANAZone {
    string name;
    string tz;
    string summer;
}

IANAZone[string] zones = ["""

for z in zones:
    out.append(f'"{z.name}": IANAZone("{z.name}", "{z.tz}", "{z.summer}"),')

with open(os.path.join('source', 'iana.d'), 'w', newline='\n') as f:
    f.write(top + '\n')
    f.write('\n'.join(out))
    f.write('\n];\n')

with open('tz.txt', 'w') as uf:
    uf.write('\n'.join(set(uniq)))
